### ISSUE TITLE
Juno Support

### ISSUE THREAD

**Issue by gravitano** [p0pye/gala-elementary-alt-tab-switcher#2]
Hey,

Do you have plan to make this app work in Elementary OS Juno?

Thanks!

**Comment by baragatti** [comment]
I managed to compile it. Here's how I've done.

First install all dependencies
```
sudo apt install cmake build-essential valac libgala-dev libwnck-3-dev libgranite-dev
```

Then build from sources (follow Git project readme).

Finally, enable window preview
```
gsettings set org.pantheon.desktop.gala.plugins.elementary-alt-tab preview-in-switcher true
```

This should work. And if you need to modify any setting, download `dconf-editor` (GUI Tool)
```
sudo apt install dconf-editor -y
```
The settings are located in `/org/pantheon/desktop/gala/plugins/elementary-alt-tab`

**Comment by baragatti** [comment]
I managed to compile it. Here's how I've done.

First install all dependencies
```
sudo apt install cmake build-essential valac libgala-dev libwnck-3-dev libgranite-dev
```

Clone or download and extract the project to a folder, open a terminal and navigate to inside the folder.

Then build from sources (like Git project readme)
```
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr ..
make
sudo make install
```

(Optional) If you want to enable window preview, execute
```
gsettings set org.pantheon.desktop.gala.plugins.elementary-alt-tab preview-in-switcher true
```

(Optional) If you want to modify any setting, download `dconf-editor` (GUI Tool)
```
sudo apt install dconf-editor -y
```
And navigate to `/org/pantheon/desktop/gala/plugins/elementary-alt-tab`


Finally, restart system or execute `gala --replace` in your terminal.

**Comment by gravitano** [comment]
Thanks @baragatti that works for me too!
