### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by racsoce** [p0pye/gala-elementary-alt-tab-switcher#4]
I need some help to uninstall this plugin, I tried reinstalling gala and pantheon but no success,

Thanks,

**Comment by sempasha** [comment]
Just remove files which were installed during `sudo make install`, in my case there is `sudo rm /usr/share/glib-2.0/schemas/org.pantheon.desktop.gala.plugins.elementary-alt-tab.gschema.xml /usr/lib/x86_64-linux-gnu/gala/plugins/libgala-elementary-alt-tab.so`.
Then, restart system or execute `gala --replace`.

**Comment by racsoce** [comment]
Yes, that works good, Thanks,
