### ISSUE TITLE
Freezes on Juno

### ISSUE THREAD

**Issue by jovanovic-milos** [p0pye/gala-elementary-alt-tab-switcher#5]
Whenever i try to switch tabs it freezes.

The error i get:
gala.desktop[9800]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x1c00003 (wingpanel)

**Comment by kennell** [comment]
I am having the same problem on Juno. I played around and wrote a hacky patch that fixes the bad timestamp issue (see https://github.com/kennell/gala-elementary-alt-tab-switcher/commit/ddb5e4bdd793e2d8b8055c87745e64f261692afb) -- this seems to delay the freezing issue for a few minutes, but it still will eventualy crash 🙁

**Comment by kennell** [comment]
After some further investigation, there seems to be another problem with Juno. The tab switcher widget will freeze if a application window title contains non-ASCII chars:

```
gala[1197]: Invalid UTF-8 string passed to pango_layout_set_text()
```

I solved this by commenting out the lines of code where the text is set for the little caption box under the icons here: https://github.com/kennell/gala-elementary-alt-tab-switcher/commit/9737aa8e3a2a722531f7f3e0a95399cd9146e658 (see lines 434 and 454). With this little hack i am no longer experiencing crashes so far. So if you don't need captions, this should work!

I am not really familiar with the Vala programming language, so this is just a temporary fix. It should be trivial to fix the UTF-8 issues for someone who is experienced with Vala.

**Comment by theocodes** [comment]
Hey

Unfortunately, the changes suggested did not work for me. I've had to re-map the key binding to 'Show all windows' as it keeps freezing everything. How can I revert it back to the default switcher?

Thanks

**EDIT:**

I've figured it out... Here's what I did in case anyone else struggles with it.

I've noticed the `build/install_manifest.txt` file and deleted both files listed there. Restarted and voila!

This is the second project aimed at addressing the issue and the second to get abandoned which is a shame... Unfortunately don't know vala/gtk enough to have a go at it myself but who knows.. maybe some day... :)

**Comment by KaappoRaivio** [comment]
> After some further investigation, there seems to be another problem with Juno. The tab switcher widget will freeze if a application window title contains non-ASCII chars:
> 
> ```
> gala[1197]: Invalid UTF-8 string passed to pango_layout_set_text()
> ```
> 
> I solved this by commenting out the lines of code where the text is set for the little caption box under the icons here: [kennell@9737aa8](https://github.com/kennell/gala-elementary-alt-tab-switcher/commit/9737aa8e3a2a722531f7f3e0a95399cd9146e658) (see lines 434 and 454). With this little hack i am no longer experiencing crashes so far. So if you don't need captions, this should work!
> 
> I am not really familiar with the Vala programming language, so this is just a temporary fix. It should be trivial to fix the UTF-8 issues for someone who is experienced with Vala.

This worked also for me. Also, I noticed that there is an option called `caption-visible` in the config, which probably achieves the same thing although I haven't tested.

**Comment by jibbo** [comment]
Hi everyone, I hope I don't bother you since you all probably moved on from this project, but I think I fixed the problems described here since they were also happening on my machine. While we wait for an answer from p0pye maybe you could try it out from my fork [here](https://github.com/jibbo/gala-elementary-alt-tab-switcher) and let me know? @kennell I added also your patch, hope you don't mind :sweat: !

Thanks a lot!

**Comment by kennell** [comment]
@jibbo No problem, feel free to do so. Not using eOS currently tho, so can't test it right now 😬

**Comment by dagolinuxoid** [comment]
@jibbo After installing all necessary dependencies I cloned your fork and installed it on elementary 5.1 Hera. I customized a bit the switcher - disabled animations, the ugly captions and changed its "css" . I'm pretty satisfied with the build - it works fast, has decent look  and with NO issues. Kudos to you.

**Comment by shved** [comment]
I assume you could just turn off the captions with dconf it it will work as it is. I've tried the configuration suggested here in the answer and it works well. 

https://elementaryos.stackexchange.com/questions/342/how-to-change-alttab-behavior
